name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt dependencies
        run: |
          chmod +x install_packages.sh
          ./install_packages.sh

      # Add additional steps to deploy your app
